<a href="https://colab.research.google.com/github/navrgithub/NLP_Authorship_Attribution/blob/main/Bert_Task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 41.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 11.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 24.6 MB/s eta 0:00:00


In [4]:
import pandas as pd
df = pd.read_csv('final_task1_data.csv')
df.head()

T1  \
0  turkey and russia announce ceasefire in northw...   
1  latest headlines on cnn business tl;dr the fed...   
2  explore chernobyl's exclusion zone in 360â° (...   
3  china and japan's budding relationship in the ...   
4  a state-by-state breakdown of us coronavirus c...   

                                                  T2  Same_OR_Not  
0  no one can protect these syrian kids from the ...            1  
1  coronavirus threat to tokyo 2020 is 'heartbrea...            1  
2  ski at austria's soelden resort on saturday, t...            1  
3  will warmer weather help fight the coronavirus...            1  
4  tv shows to help you find your happy place rig...            1

In [5]:
import torch
import numpy as np
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained('bert-base-cased')
labels = {0:0, 1:1}

class Dataset(torch.utils.data.Dataset):

    def __init__(self, df):

        self.labels = [labels[label] for label in df['label']]
        self.texts = [tokenizer(str(text), 
                               padding='max_length', max_length = 512, truncation=True,
                                return_tensors="pt") for text in df['text']]

    def classes(self):
        return self.labels

    def __len__(self):
        return len(self.labels)

    def get_batch_labels(self, idx):
        # Fetch a batch of labels
        return np.array(self.labels[idx])

    def get_batch_texts(self, idx):
        # Fetch a batch of inputs
        return self.texts[idx]

    def __getitem__(self, idx):

        batch_texts = self.get_batch_texts(idx)
        batch_y = self.get_batch_labels(idx)

        return batch_texts, batch_y

In [6]:
np.random.seed(112)
df_train, df_val, df_test = np.split(df.sample(frac=1, random_state=42), 
                                     [int(.8*len(df)), int(.9*len(df))])

print(len(df_train),len(df_val), len(df_test))
print(df_train.head())
print(df_val.head())

9240 1155 1155
                                                      T1  \
4975   jenna dewan welcomes new baby of the system an...   
5912   gloria gaynor fights coronavirus by taking her...   
970    china wants to take a victory lap over its han...   
5419   china coronavirus: eating wild animals made il...   
11537  Ski at Austria's Soelden resort soelden, austr...   

                                                      T2  Same_OR_Not  
4975   jenna dewan welcomes new baby life in is it, a...            0  
5912   beyond earth: a vr experience of time from at ...            1  
970    No, DNA is not the key to protecting Earth's t...            0  
5419   Big Tech's honeymoon with the world's second-l...            0  
11537  'Little America' brings a warm look at immigra...            1  
                                                      T1  \
6979   | | 'bachelor' peter weber and madison prewett...   
1827   ski at austria's soelden resort. " i'm sorry, ...   
9154   1. We

In [7]:
from torch import nn
from transformers import BertModel

class BertClassifier(nn.Module):

    def __init__(self, dropout=0.5):

        super(BertClassifier, self).__init__()

        self.bert = BertModel.from_pretrained('bert-base-cased')
        self.dropout = nn.Dropout(dropout)
        self.linear = nn.Linear(768, 5)
        self.relu = nn.ReLU()

    def forward(self, input_id, mask):

        _, pooled_output = self.bert(input_ids= input_id, attention_mask=mask,return_dict=False)
        dropout_output = self.dropout(pooled_output)
        linear_output = self.linear(dropout_output)
        final_layer = self.relu(linear_output)

        return final_layer

In [9]:
from torch.optim import Adam
from tqdm import tqdm

def train(model, train_data, val_data, learning_rate, epochs):

    # train_data = train_data.values.tolist()
    # val_data = val_data.values.tolist()
    train, val = Dataset(train_data), Dataset(val_data)

    train_dataloader = torch.utils.data.DataLoader(train, batch_size=2, shuffle=True)
    val_dataloader = torch.utils.data.DataLoader(val, batch_size=2)

    use_cuda = torch.cuda.is_available()
    device = torch.device("cuda" if use_cuda else "cpu")

    criterion = nn.CrossEntropyLoss()
    optimizer = Adam(model.parameters(), lr= learning_rate)

    if use_cuda:

            model = model.cuda()
            criterion = criterion.cuda()

    for epoch_num in range(epochs):

            total_acc_train = 0
            total_loss_train = 0

            for train_input, train_label in tqdm(train_dataloader):

                train_label = train_label.to(device)
                mask = train_input['attention_mask'].to(device)
                input_id = train_input['input_ids'].squeeze(1).to(device)

                output = model(input_id, mask)
                
                batch_loss = criterion(output, train_label.long())
                total_loss_train += batch_loss.item()
                
                acc = (output.argmax(dim=1) == train_label).sum().item()
                total_acc_train += acc

                model.zero_grad()
                batch_loss.backward()
                optimizer.step()
            
            total_acc_val = 0
            total_loss_val = 0

            with torch.no_grad():

                for val_input, val_label in val_dataloader:

                    val_label = val_label.to(device)
                    mask = val_input['attention_mask'].to(device)
                    input_id = val_input['input_ids'].squeeze(1).to(device)

                    output = model(input_id, mask)

                    batch_loss = criterion(output, val_label.long())
                    total_loss_val += batch_loss.item()
                    
                    acc = (output.argmax(dim=1) == val_label).sum().item()
                    total_acc_val += acc
            
            print(
                f'Epochs: {epoch_num + 1} | Train Loss: {total_loss_train / len(train_data): .3f} \
                | Train Accuracy: {total_acc_train / len(train_data): .3f} \
                | Val Loss: {total_loss_val / len(val_data): .3f} \
                | Val Accuracy: {total_acc_val / len(val_data): .3f}')
                  
EPOCHS = 5
model = BertClassifier()
LR = 1e-6
              
train(model, df_train, df_val, LR, EPOCHS)

In [ ]:
def evaluate(model, test_data):

    test = Dataset(test_data)

    test_dataloader = torch.utils.data.DataLoader(test, batch_size=2)

    use_cuda = torch.cuda.is_available()
    device = torch.device("cuda" if use_cuda else "cpu")

    if use_cuda:

        model = model.cuda()

    total_acc_test = 0
    with torch.no_grad():

        for test_input, test_label in test_dataloader:

              test_label = test_label.to(device)
              mask = test_input['attention_mask'].to(device)
              input_id = test_input['input_ids'].squeeze(1).to(device)

              output = model(input_id, mask)
              # print(output)

              acc = (output.argmax(dim=1) == test_label).sum().item()
              total_acc_test += acc
    
    print(f'Test Accuracy: {total_acc_test / len(test_data): .3f}')
    
evaluate(model, df_test)

tensor([[0.2056, 8.7740, 0.0000, 0.0000, 0.0000],
        [0.1877, 8.4887, 0.0000, 0.0000, 0.0000]], device='cuda:0')
tensor([[1.3324, 8.1836, 0.0000, 0.0000, 0.0000],
        [0.4270, 8.2165, 0.0000, 0.0000, 0.0000]], device='cuda:0')
tensor([[0.6654, 9.5485, 0.0000, 0.0000, 0.0000],
        [2.7699, 7.7954, 0.0000, 0.0000, 0.0000]], device='cuda:0')
tensor([[7.1238, 0.5455, 0.0000, 0.0000, 0.0000],
        [5.0044, 7.0746, 0.0000, 0.0000, 0.0000]], device='cuda:0')
tensor([[1.2341, 9.5317, 0.0000, 0.0000, 0.0000],
        [0.4739, 8.6142, 0.0000, 0.0000, 0.0000]], device='cuda:0')
tensor([[1.0191, 8.0255, 0.0000, 0.0000, 0.0000],
        [1.5889, 7.3141, 0.0000, 0.0000, 0.0000]], device='cuda:0')
tensor([[0.3399, 8.9245, 0.0000, 0.0000, 0.0000],
        [0.9126, 9.4168, 0.0000, 0.0000, 0.0000]], device='cuda:0')
tensor([[1.1043, 9.3088, 0.0000, 0.0000, 0.0000],
        [0.0000, 8.8321, 0.0000, 0.0000, 0.0000]], device='cuda:0')
tensor([[1.9242, 9.4929, 0.0000, 0.0000, 0.0000],
      